# Generated by Django 5.0.4 on 2024-06-10 17:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_add_teacher_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("duration", models.DurationField(verbose_name="Продолжительность")),
                ("specialization", models.ManyToManyField(to="users.specialization")),
            ],
            bases=(users.models.DateTimeMixin, models.Model),
        ),
    ]
