# Generated by Django 5.0.4 on 2024-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education_process", "0003_rename_id_group_course_group"),
        ("users", "0003_rename_id_user_student_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="student",
        ),
        migrations.AddField(
            model_name="group",
            name="student",
            field=models.ManyToManyField(to="users.student"),
        ),
    ]
