# Generated by Django 5.0.4 on 2024-05-12 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_student_teacher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="id_user",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="id_user",
            new_name="user",
        ),
    ]
