# Generated by Django 5.0.4 on 2024-05-21 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_id_user_student_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
