# Generated by Django 5.0.4 on 2024-06-10 17:54

import datetime

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education_process", "0007_add_ctest_model"),
        ("users", "0004_add_teacher_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "date_formation",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 6, 10, 17, 54, 2, 994508, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Дата образования",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education_process.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(to="users.student", verbose_name="Студенты"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            bases=(users.models.DateTimeMixin, models.Model),
        ),
    ]
